### ISSUE TITLE
Flashing a NodeMCU

### ISSUE THREAD

**Issue by Ronel308** [senceit/micropy-node#2]
Hi Niel,
I have uploaded the files you mentioned but can not change the directory as per in Command prompt!
Please assist.

**Comment by nielswart** [comment]
Please make sure you have done the following:

1. You downloaded the repository and unzipped it in a directory
2. You can navigate to that directory with the command prompt
3. You have Node installed - check with `node --version`
4. You have python installed - check with `python --version`

If you can complete these steps you will be able to follow the README to flash the NodeMCU

**Comment by nielswart** [comment]
> Hi Niel,
> I have uploaded the files you mentioned but can not change the directory as per in Command prompt!
> Please assist.

Please make sure you have done the following:

1. You downloaded the repository and unzipped it in a directory
2. You can navigate to that directory with the command prompt
3. You have Node installed - check with `node --version`
4. You have python installed - check with `python --version`

If you can complete these steps you will be able to follow the README to flash the NodeMCU

**Comment by Ronel308** [comment]
Does the Arduino IDE file has to be downloaded on the NodeMCU as well?

**Comment by nielswart** [comment]
No this is not an Arduino project.
________________________________

**Comment by Ronel308** [comment]
Thanks, I will delete the Arduino IDE file.

**Comment by Ronel308** [comment]
Good day,

Please watch out for this guy, his name is Niel Swart, founder of Senceilt,he has been working on my dam water level project for the past six months without it working and now he accuses me of downloading software without his permission, he also said that I am dishonest with him due to the fact that his system is not working.
Kind regards,
Kobus Steenkamp

**Comment by nielswart** [comment]
Thanks Kobus! Appreciate the time you have taken.
